stages:
  load_clean:
    cmd: python  src/stages/data_cleaning.py --config=params.yaml
    deps:
    - data/census.csv
    - src/stages/data_cleaning.py
    - src/utils/data_clean.py

    params:
    - load_clean
    outs:
    - data/clean_census.csv
  test_clean:
    cmd: pytest  src/stages/test_data_cleaning.py
    deps: 
    - src/stages/test_data_cleaning.py
    - src/utils/data_clean.py
    - data/clean_census.csv

  data_split:
    cmd: python src/stages/data_split.py --config params.yaml
    deps: 
    - src/stages/data_split.py
    - data/clean_census.csv
    params: 
    - base.random_state
    - data_split
    outs:
    - data/train/train_set.csv
    - data/train/test_set.csv
  preprocess:
    cmd: python src/stages/preprocess.py --config=params.yaml
    deps: 
    - src/ml_model/data.py
    - data/train/train_set.csv
    - data/train/test_set.csv
    params: 
    - preprocess
    outs:
    - artifacts/encoders/label_encoder.gz
    - artifacts/encoders/cat_features_encoder.gz
    - artifacts/encoders/num_features_encoder.gz
    - data/train/features/x_train.npy
    - data/train/features/y_train.npy
    - data/train/features/x_test.npy
    - data/train/features/y_test.npy
  train_model:
    cmd: python src/stages/train_model.py --config=params.yaml
    deps:
    - src/ml_model/data.py
    - src/ml_model/model.py
    - artifacts/encoders/label_encoder.gz
    - artifacts/encoders/cat_features_encoder.gz
    - artifacts/encoders/num_features_encoder.gz
    - data/train/features/x_train.npy
    - data/train/features/y_train.npy
    - data/train/features/x_test.npy
    - data/train/features/y_test.npy
    params: 
    - train
    - preprocess
    metrics:
    - reports/metrics.json:
        cache: false
    outs:
    - artifacts/model/census-gradient-boosting-classifier.gz
    
  slice_validation:
    cmd: python  src/stages/slice_check.py --config=params.yaml
    deps:
    - src/stages/slice_check.py
    - artifacts/encoders/label_encoder.gz
    - artifacts/encoders/cat_features_encoder.gz
    - artifacts/encoders/num_features_encoder.gz
    - artifacts/model/census-gradient-boosting-classifier.gz
    params:
    - preprocess
    - train
    outs:
    - reports/slice_output.txt:
        cache: false
  
  test_model_infer:
    cmd: pytest  src/stages/test_model_steps.py
    deps: 
    - src/stages/test_model_steps.py
    - artifacts/encoders/label_encoder.gz
    - artifacts/encoders/cat_features_encoder.gz
    - artifacts/encoders/num_features_encoder.gz
    - artifacts/model/census-gradient-boosting-classifier.gz
    params:
    - preprocess
    - train
    